# Generated by Django 4.0.2 on 2022-02-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_ip', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('signature', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True)),
                ('disabled_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
